#server info
server:
  port: 8000

spring:
  #swagger setting
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #JPA setting
  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: create
  #DB setting
  datasource:
    url: jdbc:mariadb://localhost:3306/snack_bar?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

#jwt
jwt:
  secret: SNACKBARJWTSECRETKEY
  access-expired: 1800
